/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVagasRouteImport } from './routes/dashboard.vagas'
import { Route as DashboardUsuariosRouteImport } from './routes/dashboard.usuarios'
import { Route as DashboardProjetosRouteImport } from './routes/dashboard.projetos'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard.perfil'
import { Route as DashboardMinhasVagasRouteImport } from './routes/dashboard.minhas-vagas'
import { Route as DashboardMeusProjetosRouteImport } from './routes/dashboard.meus-projetos'
import { Route as DashboardMeusEventosRouteImport } from './routes/dashboard.meus-eventos'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardEventosRouteImport } from './routes/dashboard.eventos'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVagasRoute = DashboardVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsuariosRoute = DashboardUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjetosRoute = DashboardProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMinhasVagasRoute = DashboardMinhasVagasRouteImport.update({
  id: '/minhas-vagas',
  path: '/minhas-vagas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeusProjetosRoute = DashboardMeusProjetosRouteImport.update({
  id: '/meus-projetos',
  path: '/meus-projetos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeusEventosRoute = DashboardMeusEventosRouteImport.update({
  id: '/meus-eventos',
  path: '/meus-eventos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventosRoute = DashboardEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/canais': typeof CanaisRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vagas': typeof VagasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/eventos': typeof DashboardEventosRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/meus-eventos': typeof DashboardMeusEventosRoute
  '/dashboard/meus-projetos': typeof DashboardMeusProjetosRoute
  '/dashboard/minhas-vagas': typeof DashboardMinhasVagasRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/projetos': typeof DashboardProjetosRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/vagas': typeof DashboardVagasRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/canais': typeof CanaisRoute
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vagas': typeof VagasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/eventos': typeof DashboardEventosRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/meus-eventos': typeof DashboardMeusEventosRoute
  '/dashboard/meus-projetos': typeof DashboardMeusProjetosRoute
  '/dashboard/minhas-vagas': typeof DashboardMinhasVagasRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/projetos': typeof DashboardProjetosRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/vagas': typeof DashboardVagasRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/canais': typeof CanaisRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vagas': typeof VagasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/eventos': typeof DashboardEventosRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/meus-eventos': typeof DashboardMeusEventosRoute
  '/dashboard/meus-projetos': typeof DashboardMeusProjetosRoute
  '/dashboard/minhas-vagas': typeof DashboardMinhasVagasRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/projetos': typeof DashboardProjetosRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/vagas': typeof DashboardVagasRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/canais'
    | '/dashboard'
    | '/eventos'
    | '/faq'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/vagas'
    | '/dashboard/configuracoes'
    | '/dashboard/eventos'
    | '/dashboard/logs'
    | '/dashboard/meus-eventos'
    | '/dashboard/meus-projetos'
    | '/dashboard/minhas-vagas'
    | '/dashboard/perfil'
    | '/dashboard/projetos'
    | '/dashboard/usuarios'
    | '/dashboard/vagas'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/canais'
    | '/eventos'
    | '/faq'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/vagas'
    | '/dashboard/configuracoes'
    | '/dashboard/eventos'
    | '/dashboard/logs'
    | '/dashboard/meus-eventos'
    | '/dashboard/meus-projetos'
    | '/dashboard/minhas-vagas'
    | '/dashboard/perfil'
    | '/dashboard/projetos'
    | '/dashboard/usuarios'
    | '/dashboard/vagas'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/canais'
    | '/dashboard'
    | '/eventos'
    | '/faq'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/vagas'
    | '/dashboard/configuracoes'
    | '/dashboard/eventos'
    | '/dashboard/logs'
    | '/dashboard/meus-eventos'
    | '/dashboard/meus-projetos'
    | '/dashboard/minhas-vagas'
    | '/dashboard/perfil'
    | '/dashboard/projetos'
    | '/dashboard/usuarios'
    | '/dashboard/vagas'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CanaisRoute: typeof CanaisRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventosRoute: typeof EventosRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  VagasRoute: typeof VagasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vagas': {
      id: '/dashboard/vagas'
      path: '/vagas'
      fullPath: '/dashboard/vagas'
      preLoaderRoute: typeof DashboardVagasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usuarios': {
      id: '/dashboard/usuarios'
      path: '/usuarios'
      fullPath: '/dashboard/usuarios'
      preLoaderRoute: typeof DashboardUsuariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projetos': {
      id: '/dashboard/projetos'
      path: '/projetos'
      fullPath: '/dashboard/projetos'
      preLoaderRoute: typeof DashboardProjetosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/minhas-vagas': {
      id: '/dashboard/minhas-vagas'
      path: '/minhas-vagas'
      fullPath: '/dashboard/minhas-vagas'
      preLoaderRoute: typeof DashboardMinhasVagasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/meus-projetos': {
      id: '/dashboard/meus-projetos'
      path: '/meus-projetos'
      fullPath: '/dashboard/meus-projetos'
      preLoaderRoute: typeof DashboardMeusProjetosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/meus-eventos': {
      id: '/dashboard/meus-eventos'
      path: '/meus-eventos'
      fullPath: '/dashboard/meus-eventos'
      preLoaderRoute: typeof DashboardMeusEventosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/eventos': {
      id: '/dashboard/eventos'
      path: '/eventos'
      fullPath: '/dashboard/eventos'
      preLoaderRoute: typeof DashboardEventosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardEventosRoute: typeof DashboardEventosRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMeusEventosRoute: typeof DashboardMeusEventosRoute
  DashboardMeusProjetosRoute: typeof DashboardMeusProjetosRoute
  DashboardMinhasVagasRoute: typeof DashboardMinhasVagasRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardProjetosRoute: typeof DashboardProjetosRoute
  DashboardUsuariosRoute: typeof DashboardUsuariosRoute
  DashboardVagasRoute: typeof DashboardVagasRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardEventosRoute: DashboardEventosRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMeusEventosRoute: DashboardMeusEventosRoute,
  DashboardMeusProjetosRoute: DashboardMeusProjetosRoute,
  DashboardMinhasVagasRoute: DashboardMinhasVagasRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardProjetosRoute: DashboardProjetosRoute,
  DashboardUsuariosRoute: DashboardUsuariosRoute,
  DashboardVagasRoute: DashboardVagasRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CanaisRoute: CanaisRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventosRoute: EventosRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  VagasRoute: VagasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
